mysite/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
#from .views import register, dashboard, edit, edit_password, password_reset, password_reset_confirm

app_name = 'accounts'

urlpatterns = [

    path('entrar/', auth_views.LoginView.as_view
        (template_name='accounts/entrar.html'), name='login'),
    path('sair/', auth_views.LogoutView.as_view
        (template_name='index.html'), name='logout'),
]

mysite/core/urls.py
from django.urls import path
from .views import home

app_name = 'core'

urlpatterns = [
    path('', home, name='home'),

]

mysite/tools/urls.py
from django.urls import path
from .views import hss, metalDuro

app_name = 'tools'

urlpatterns = [

    path('tabela/hss', hss, name='hss'),
    path('tabela/metalDuro', metalDuro, name='metalDuro'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include



app_name = 'mysite'

urlpatterns = [
    path('', include('mysite.core.urls', namespace='core')),
    path('conta/', include('mysite.accounts.urls', namespace='accounts')),
    path('ferramentas/', include('mysite.tools.urls', namespace='tools')),
    path('admin/', admin.site.urls),
]

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/core/models.py
from django.db import models

# Create your models here.

mysite/tools/models.py
from django.db import models


class TypeItem(models.Model):
    description = models.CharField('Descrição', max_length=150, blank=False)

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'Descrição'
        verbose_name_plural = 'Descrições'


class Item(models.Model):
    type = models.ForeignKey(TypeItem, related_name='Descrição', blank=False, on_delete=models.CASCADE)
    stock_code = models.IntegerField('Código Interno', blank=True, null=True)
    name = models.CharField('Nome', max_length=100, blank=False)
    diameter = models.DecimalField('Diametro', max_digits=5, decimal_places=2, blank=False)
    cutterLength = models.DecimalField('Altura de Corte', max_digits=5,decimal_places=2, blank=False)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Nome'
        verbose_name_plural = 'Nomes'
        ordering = ['diameter']

mysite/accounts/views.py
from django.shortcuts import render

# Create your views here.

mysite/core/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'index.html')

mysite/tools/views.py
from django.shortcuts import render, get_object_or_404
from .models import Item, TypeItem

def hss(request):
    broca = Item.objects.filter(type=1)
    tipo = TypeItem.objects.get(pk=1)
    template_name = 'tools/tabela.html'
    context = {
        'broca': broca,
        'tipo': tipo
    }
    return render(request, template_name, context)

def metalDuro(request):
    tipo = TypeItem.objects.get(pk=2)
    broca = Item.objects.filter(type_id=2).order_by('diameter',)
    template_name = 'tools/tabela.html'
    context = {
        'tipo': tipo,
        'broca': broca
    }
    return render(request, template_name, context)

mysite/accounts/templates/accounts/entrar.html
{% extends "base.html" %}


{% block content %}
{% load widget_tweaks %}
<section class="product iphone-x">
        <div class="login-dark">
            {% csrf_token %}
            <form method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <h2 class="sr-only">Login Form</h2>
            <div class="illustration"><i class="icon ion-ios-locked-outline"></i></div>
            {% for field in form %}
            <div class="form-group">
                {{ field.label_tag }}
                {{field|add_class:"form-control"}}
                {{ field.errors }}
            </div>
            {% endfor %}
                <div class="form-group"><button class="btn btn-primary btn-block">Log In</button></div>
            </form>
          <section></section>
        </div>
    </section>

{% endblock %}

mysite/core/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Gama website</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/ionicons.min.css' %}">
    <link rel="stylesheet" href="{% static 'fonts/simple-line-icons.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Cookie">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Slab:300,400|Roboto:300,400,700">
    <link rel="stylesheet" href="{% static 'css/Data-Table.css' %}">
    <link rel="stylesheet" href="{% static 'css/Footer-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'css/Login-Form-Dark.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="{% static 'js/datatables.min.css' %}">
</head>

<body>
    <nav class="navbar navbar-dark navbar-expand-sm fixed-top bg-dark">
        <div class="container-fluid"><button data-toggle="collapse" data-target="#navcol-1" class="navbar-toggler"><span class="sr-only">Toggle navigation</span><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav text-justify flex-grow-1 justify-content-between">
                    <li class="nav-item" role="presentation"><a class="nav-link" href="#"><img src="{% static 'img/logo-header.png' %}"></a></li>
                </ul>
            </div>
            <div class="collapse navbar-collapse" id="navcol-1">
                <ul class="nav navbar-nav text-justify d-lg-flex flex-grow-1 justify-content-between align-items-lg-center">
                    <li class="nav-item d-lg-flex align-items-lg-start" role="presentation"><a class="nav-link" href="{% url 'core:home' %}">Inicio</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item d-lg-flex align-items-lg-start" role="presentation">
                        <li class="nav-item dropdown"><a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false" href="#">Brocas&nbsp;</a>
                            <div class="dropdown-menu" role="menu">
                                <a class="dropdown-item" role="presentation" href="{% url 'tools:metalDuro' %}">Brocas Metal Duro</a>
                                <a class="dropdown-item" role="presentation" href="{% url 'tools:hss' %}">Brocas HSS</a></div>
                        </li>
                    </li>
                    {% endif %}

                    <li class="nav-item" role="presentation"><a class="nav-link" href="#">Sobre</a></li>
                    <li class="nav-item" role="presentation"><a class="nav-link" href="#">Contato</a></li>
                    {% if user.is_authenticated %}
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'accounts:logout' %}">Sair</a></li>
                    {% else %}
                    <li class="nav-item" role="presentation"><a class="nav-link" href="{% url 'accounts:login' %}">Entrar</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>


    {% block content %} <!--aqui entra o content-->  {% endblock %}

    
    <div class="footer-dark">
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Serviços</h3>
                        <ul>
                            <li><a href="#">Acesse o Site</a></li>
                            <li></li>
                            <li></li>
                        </ul>
                    </div>
                    <div class="col-sm-6 col-md-3 item">
                        <h3>Sobre</h3>
                        <ul>
                            <li><a href="#">Time</a></li>
                            <li></li>
                            <li><a href="#">Carreiras</a></li>
                        </ul>
                    </div>
                    <div class="col-md-6 item text">
                        <h3>Empresa GAMA</h3>
                        <p><br>A empresa vem se destacando no segmento de fabricação de moldes para injeção de plásticos e alumínio, mantendo o foco de se posicionar entre as melhores do país no setor de ferramentaria.<br><br></p>
                    </div>
                    <div class="col item social"><a href="#"><i class="icon ion-social-linkedin"></i></a><a href="#"><i class="icon ion-email"></i></a></div>
                </div>
                <p class="copyright">Gama © 2019</p>
            </div>
        </footer>
    </div>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.15/js/dataTables.bootstrap.min.js"></script>
    {% block script %} <!--aqui entra o script-->  {% endblock %}
</body>

</html>

mysite/core/templates/index.html
{% extends "base.html" %}
{% block content %}

<section class="product iphone-x">
    <h1>Bem vindo a Engenharia Gama.&nbsp;</h1>
    <h2>Esta página é destinada a equipe de engenharia.</h2>
    <h2 class="paragrafo">Aproveite!</h2>
</section>

{% endblock %}

mysite/tools/templates/tools/tabela.html
{% extends "base.html" %}


{% block content %}
{% load static %}

<section class="product iphone-x">
        <h2>Brocas de {{ tipo.description }}.</h2>
        <div class="tabela">

            <table id="myTable" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th class="th">Código</th>
                <th class="th">Nome</th>
                <th class="th">Diametro</th>
                <th class="th">Altura de Corte</th>
            </tr>
        </thead>
            <tbody>
            {% for item in broca %}
            <tr>
                <td>{{ item.stock_code }}</td>
                <td>{{ item.name }}</td>
                <td>Ø{{ item.diameter }}</td>
                <td>{{ item.cutterLength }}</td>
                {% endfor %}
            </tr>
            </tbody>
    </table>

	</div>
    </section>

{% endblock %}
{% block script %}
	<script>


           $(document).ready(function() {
    $('#myTable').DataTable( {
        "language": {
            "lengthMenu": "Vizualizar _MENU_ linhas por página",
            "zeroRecords": "Nada encontrado - desculpe",
            "info": "Vizualizando página _PAGE_ de _PAGES_",
            "infoEmpty": "Nenhum registro disponível",
            "search": "Pesquisar:",
            "infoFiltered": "(filtro de _MAX_ linhas lidas)",
        "paginate": {
            "previous": "Anterior",
            "next": "Próximo"

        }

        }



    } );
} );

</script>


{% endblock %}